/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jyzetjvnhmcfhjosegmn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5emV0anZuaG1jZmhqb3NlZ21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1ODcwMDcsImV4cCI6MjA4MTE2MzAwN30.yyMqxlJeX4-J8t0ywfwkwTqKqZSyCBbFo3DCbu7ePLU"
